#spawn Categories(MONSTER, CREATURE, ... defaults..., custom pools from other mods
spawnCategories = ["MONSTER,73", "CREATURE,10", "AMBIENT,14", "AXOLOTLS,5", "UNDERGROUND_WATER_CREATURE,5", "WATER_CREATURE,5", "WATER_AMBIENT,20"]

